version: "2"
run:
  timeout: 10m
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - goconst
    - godot
    - govet
    - grouper
    - ineffassign
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnil
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - rowserrcheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  settings:
    staticcheck:
      checks:
          - S1*
formatters:
  enable:
    - gofmt
    - goimports
